name: Debug Azure Credentials

on:
  workflow_dispatch:

jobs:
  debug-azure-cred:
    runs-on: ubuntu-latest

    steps:
      - name: Check if secret is available
        run: |
          if [ -z "${{ secrets.AZURE_CREDENTIALS_dev }}" ]; then
            echo "::error::❌ Secret is empty or not defined!"
          exit 1
          else
           echo "::notice::✅ Secret is available"
          fi

      - name: Print list of JSON keys (safely)
        run: echo '${{ secrets.AZURE_CREDENTIALS_dev }}' | jq -r 'keys'
          
      - name: Check if secret exists
        run: |
          if [ -z "${{ secrets.AZURE_CREDENTIALS_dev }}" ]; then
            echo "::error::❌ Secret 'AZURE_CREDENTIALS_DEV' is missing or empty"
            exit 1
          else
            echo "::notice::✅ Secret 'AZURE_CREDENTIALS_DEV' is present"
          fi



      
